import {test} from 'node:test';import assert from 'node:assert/strict';import {Worker} from 'node:worker_threads';
function start({failOnce=false}={}){
  const source=`import {parentPort} from 'node:worker_threads';import {readFile} from 'node:fs/promises';let fail=${failOnce};globalThis.fetch=async url=>{if(fail&&String(url).endsWith('.wasm')){fail=false;return new Response('',{status:503});}return new Response(await readFile(new URL(url)));};globalThis.postMessage=data=>parentPort.postMessage(data);globalThis.onmessage=null;parentPort.on('message',data=>globalThis.onmessage?.({data}));await import(${JSON.stringify(new URL('./dist/worker.mjs',import.meta.url).href)});`;
  const worker=new Worker(new URL('data:text/javascript,'+encodeURIComponent(source))),messages=[];let fault;
  worker.on('message',d=>messages.push(d));worker.on('error',e=>fault=e);
  const wait=async predicate=>{const start=performance.now();while(!predicate()){if(fault)throw fault;if(performance.now()-start>10000)throw Error('Worker timed out');await new Promise(r=>setTimeout(r,15));}};
  return {worker,messages,wait};
}
test('shipped worker bootstraps JSBSim, pauses time, records CSV and resets',async()=>{
  const {worker,messages,wait}=start();try{
    await wait(()=>messages.some(d=>d.ready));assert.equal(messages.at(-1).engine,'JSBSim 1.2.4');assert.equal(messages.at(-1).elapsed,0);
    worker.postMessage({type:'turbulence',value:'light'});await wait(()=>messages.at(-1)?.weather?.turbulence==='light');worker.postMessage({type:'record',value:true});worker.postMessage({type:'pause',value:false});await wait(()=>messages.at(-1)?.elapsed>.2);
    worker.postMessage({type:'pause',value:true});await wait(()=>messages.at(-1)?.paused);const time=messages.at(-1).elapsed;await new Promise(r=>setTimeout(r,100));assert.equal(messages.at(-1).elapsed,time);
    worker.postMessage({type:'export'});await wait(()=>messages.some(d=>d.type==='csv'));const lines=messages.find(d=>d.type==='csv').csv.split('\n');assert.ok(lines.length>2);assert.equal(lines[0].split(',').length,22);assert.equal(lines[1].split(',').length,22);assert.ok(lines[0].includes('alpha_dependent_drag_N'));
    worker.postMessage({type:'reset',speed:45,altitude:2438.4});await wait(()=>messages.at(-1)?.elapsed===0&&Math.abs(-messages.at(-1).state[2]-2438.4)<.01);assert.equal(messages.at(-1).paused,true);assert.equal(messages.at(-1).weather.turbulence,'light');assert.equal(messages.at(-1).recording,false);assert.equal(messages.some(d=>d.type==='error'),false);
  }finally{await worker.terminate();}
});
test('download failure is explicit and reset retries the real engine',async()=>{
  const {worker,messages,wait}=start({failOnce:true});try{await wait(()=>messages.some(d=>d.type==='error'));assert.match(messages.at(-1).message,/download failed/);assert.equal(messages.some(d=>d.ready),false);worker.postMessage({type:'reset',speed:52,altitude:900});await wait(()=>messages.some(d=>d.ready));assert.equal(messages.at(-1).elapsed,0);assert.equal(messages.at(-1).paused,true);}finally{await worker.terminate();}
});
test('F-15 augmented controls run in worker physics loop and Direct mode persists on reset',async()=>{
 const {worker,messages,wait}=start();try{
  await wait(()=>messages.some(d=>d.ready));worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.aircraft?.key==='f15');
  worker.postMessage({type:'controls',controls:{pilot:{elevator:0,aileron:.4,rudder:0,trimOffset:0}}});worker.postMessage({type:'pause',value:false});await wait(()=>messages.at(-1)?.elapsed>.3&&messages.at(-1)?.augmentation?.enabled);assert.ok(messages.at(-1).state[10]>0);
  worker.postMessage({type:'pause',value:true});await wait(()=>messages.at(-1)?.paused);const time=messages.at(-1).elapsed;await new Promise(r=>setTimeout(r,80));assert.equal(messages.at(-1).elapsed,time);
  worker.postMessage({type:'augmentation',value:false});await wait(()=>messages.at(-1)?.augmentation===null);worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.elapsed===0);worker.postMessage({type:'controls',controls:{pilot:{elevator:0,aileron:.4,rudder:0,trimOffset:0}}});worker.postMessage({type:'pause',value:false});await wait(()=>messages.at(-1)?.elapsed>.1);assert.equal(messages.at(-1).augmentation,null);assert.equal(messages.some(d=>d.type==='error'),false);
 }finally{await worker.terminate();}
});
test('worker fires F-15 missiles, freezes them on pause and reloads on reset',async()=>{
 const {worker,messages,wait}=start();try{await wait(()=>messages.some(d=>d.ready));worker.postMessage({type:'fire'});await wait(()=>messages.at(-1)?.weapons?.remaining===0);worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.weapons?.remaining===8);worker.postMessage({type:'fire'});await new Promise(r=>setTimeout(r,60));assert.equal(messages.at(-1).weapons.remaining,8);worker.postMessage({type:'pause',value:false});worker.postMessage({type:'fire'});await wait(()=>messages.at(-1)?.weapons?.remaining===7);await wait(()=>messages.at(-1)?.weapons?.projectiles[0]?.trail.length>2);worker.postMessage({type:'pause',value:true});await wait(()=>messages.at(-1)?.paused);const saved=messages.at(-1).weapons;await new Promise(r=>setTimeout(r,80));assert.deepEqual(messages.at(-1).weapons,saved);worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.weapons?.remaining===8);assert.equal(messages.at(-1).weapons.projectiles.length,0);assert.equal(messages.some(d=>d.type==='error'),false);}finally{await worker.terminate();}
});
test('AI worker commands spawn, select and clear aircraft; pause freezes patrols',async()=>{
 const {worker,messages,wait}=start();try{await wait(()=>messages.some(d=>d.ready));worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.forces?.units.length===1);worker.postMessage({type:'target'});await wait(()=>messages.at(-1)?.forces?.selected!==null);assert.equal(messages.at(-1).forces.lock,true);worker.postMessage({type:'spawnAircraft',team:'friendly'});await wait(()=>messages.at(-1)?.forces?.units.length===2);assert.equal(messages.at(-1).forces.units[1].team,'friendly');worker.postMessage({type:'pause',value:false});await wait(()=>messages.at(-1)?.elapsed>.2);worker.postMessage({type:'pause',value:true});await wait(()=>messages.at(-1)?.paused);const saved=messages.at(-1).forces;await new Promise(r=>setTimeout(r,80));assert.deepEqual(messages.at(-1).forces,saved);worker.postMessage({type:'clearAircraft'});await wait(()=>messages.at(-1)?.forces?.units.length===0);assert.equal(messages.at(-1).forces.selected,null);worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.forces?.units.length===1);assert.equal(messages.some(d=>d.type==='error'),false);}finally{await worker.terminate();}
});
test('F-15 radar integrates scope settings, selection, power inhibition and paused scan time',async()=>{
 const {worker,messages,wait}=start();try{await wait(()=>messages.some(d=>d.ready));worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.radar?.enabled);assert.equal(messages.at(-1).radar.contacts.length,1);const id=messages.at(-1).radar.contacts[0].id;worker.postMessage({type:'radarTarget',id});await wait(()=>messages.at(-1)?.forces.selected===id);assert.equal(messages.at(-1).forces.lock,true);worker.postMessage({type:'radar',settings:{mode:'track',rangeNm:20}});await wait(()=>messages.at(-1)?.radar.mode==='track');worker.postMessage({type:'pause',value:false});await wait(()=>messages.at(-1)?.radar.time>.2);worker.postMessage({type:'pause',value:true});await wait(()=>messages.at(-1)?.paused);const radar=messages.at(-1).radar;await new Promise(r=>setTimeout(r,80));assert.deepEqual(messages.at(-1).radar,radar);worker.postMessage({type:'radar',settings:{power:false}});await wait(()=>messages.at(-1)?.radar.power===false);assert.equal(messages.at(-1).forces.lock,false);worker.postMessage({type:'reset',aircraft:'f15',speed:180,altitude:3000});await wait(()=>messages.at(-1)?.elapsed===0);assert.equal(messages.at(-1).radar.power,false);assert.equal(messages.at(-1).radar.rangeNm,20);assert.equal(messages.some(d=>d.type==='error'),false);}finally{await worker.terminate();}
});
